version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8789
    volumes:
      - .:/app
    ports:
      - "8789:8789"
    depends_on:
      - db
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=1
      - SECRET_KEY=your-secret-key
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
